name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lints
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run Tests
        run: pnpm run test
