name: Build and Deploy
on:
  push:
    branches:
      - 'main-page'

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ️
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.6.10

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lints
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Copy `CNAME` file
        run: cp CNAME out/CNAME

      - name: Create .nojekyll
        run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: page
          folder: out
          single-commit: true
