name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.10

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lints
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Compress Dist Folder
        run: zip -r build.zip dist

      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref }}
          name: ${{ env.TAG }}
          draft: true
          omitDraftDuringUpdate: true
          artifacts: build.zip
